name = "financial-calculators-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "financial-calculators-db"
database_id = "5928c053-fb18-4f3f-bf45-ad6e917ab80e"

[env.dev]
name = "financial-calculators-worker-dev"

[env.prod]
name = "financial-calculators-worker"

[[services]]
binding = "admin"
service = "admin-worker"

[env.prod.services]
binding = "admin"
service = "admin-worker-prod"
